# Generated by Django 5.2.11 on 2026-02-27 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avtar',
            field=models.ImageField(blank=True, null=True, upload_to='users/avatars/'),
        ),
    ]
