# Generated by Django 5.2.11 on 2026-03-03 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_avtar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='avtar',
            new_name='avatar',
        ),
    ]
